package booksearch.emotion_thesaurus;

public enum Sections {
	EMOTION,
	DEFINITION,
	POLARITY,
	PHYSICAL_SIGNALS,
	INTERNAL_SENSATIONS,
	MENTAL_RESPONSES,
	ACUTE_OR_LONG_TERM_CUES,
	RELATED_EMOTIONS,
	SUPPRESSED_CUES,
	WRITER_TIP
}
